### ISSUE TITLE
Adding Latest EA Papers and MEAformer Update

### ISSUE THREAD

**Issue by hackerchenzhuo** [pengfei-luo/multimodal-knowledge-graph#2]
We appreciate your remarkable work on this repository.

We would like to contribute our latest papers "[Rethinking Uncertainly Missing and Ambiguous Visual Modality in Multi-Modal Entity Alignment](https://arxiv.org/abs/2307.16210)" and [Revisit and Outstrip Entity Alignment: A Perspective of Generative Models](https://arxiv.org/abs/2305.14651) to your wonderful Repo.

Besides, we have updated the information of our MEAformer.

Please review our PR at your convenience. We've already submitted the merge request : ) 

Thanks!

**Comment by pengfei-luo** [comment]
We have merged your PR.

Thank you for your attention and contribution!
